CREATE TABLE POKEMON(
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    FAVORITE NUMBER(1,0) NOT NULL
);

CREATE UNIQUE INDEX POKEMON_PK ON POKEMON(ID);
ALTER TABLE POKEMON ADD CONSTRAINT POKEMON_PK PRIMARY KEY (ID);

CREATE TABLE POKEMON_TYPE(
    ID NUMBER NOT NULL,
    POKEMON_ID NUMBER NOT NULL,
    POKEMON_TYPE VARCHAR2(100) NOT NULL
);

CREATE UNIQUE INDEX PT_PK ON POKEMON_TYPE(ID);
ALTER TABLE POKEMON_TYPE ADD CONSTRAINT PT_PK PRIMARY KEY (ID);
ALTER TABLE POKEMON_TYPE ADD CONSTRAINT PT_FK FOREIGN KEY (POKEMON_ID) REFERENCES POKEMON(ID);